<?php

/**
 * Implements hook_features_api().
 */
function commerce_uuid_features_features_api() {
  $components = array();

  if(module_exists('commerce_product') && module_exists('commerce_uuid_product')) {
    $components['commerce_product'] = array(
      'name' => t('Commerce Product'),
      'feature_source' => TRUE,
      'default_hook' => 'commerce_uuid_features_default_products',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'file' => drupal_get_path('module', 'commerce_uuid_features') . '/features/commerce_product.features.inc',
    );
  }

  return $components;
}
